// Pinout for U3 (ESP32-WROOM-E)
// #define PIN_GND 
// #define PIN_P3V3 
#define PIN_NETNU3NENSLASHCHIP_PU 
#define PIN_LINE_L_IN GPIO_NUM_36
#define PIN_LINE_R_IN GPIO_NUM_39
#define PIN_CONFIG_IN GPIO_NUM_34
#define PIN_BUTTON_IN GPIO_NUM_35
#define PIN_MOTOR_A_PWM GPIO_NUM_32
#define PIN_MOTOR_B_PWM GPIO_NUM_33
#define PIN_MOSFET_GATE_1 GPIO_NUM_25
#define PIN_MOTOR_A_IN2 GPIO_NUM_26
// #define PIN_UNCONNECTEDNU3NADC2_CH7SLASHGPIO27NPAD12 GPIO_NUM_27
#define PIN_SD_CLK GPIO_NUM_14
#define PIN_SD_DATA2 GPIO_NUM_12
#define PIN_GND 
#define PIN_SD_DATA3 GPIO_NUM_13
// #define PIN_UNCONNECTEDNU3NNCNPAD17 
// #define PIN_UNCONNECTEDNU3NNCNPAD18 
// #define PIN_UNCONNECTEDNU3NNCNPAD19 
// #define PIN_UNCONNECTEDNU3NNCNPAD20 
// #define PIN_UNCONNECTEDNU3NNCNPAD21 
// #define PIN_UNCONNECTEDNU3NNCNPAD22 
#define PIN_SD_CMD GPIO_NUM_15
#define PIN_SD_DATA0 GPIO_NUM_2
#define PIN_ESP32_BOOT GPIO_NUM_0
#define PIN_SD_DATA1 GPIO_NUM_4
#define PIN_NSERVO_INV_1 GPIO_NUM_16
#define PIN_LED_2 GPIO_NUM_17
#define PIN_LED_1 GPIO_NUM_5
#define PIN_MOTOR_A_IN1 GPIO_NUM_18
#define PIN_MOTOR_B_IN1 GPIO_NUM_19
// #define PIN_UNCONNECTEDNU3NNCNPAD32 
#define PIN_TCA_SDA GPIO_NUM_21
#define PIN_UART_RX GPIO_NUM_3
#define PIN_UART_TX GPIO_NUM_1
#define PIN_TCA_SCL GPIO_NUM_22
#define PIN_MOTOR_B_IN2 GPIO_NUM_23
// #define PIN_GND 
// #define PIN_GND 
